### ISSUE TITLE
'validateIdToken' token returns JWT not validated payload.

### ISSUE THREAD

**Issue by irensaltali** [irensaltali/serverlessapigateway#71]
https://github.com/irensaltali/serverlessapigateway/blob/fd71be51d67621bfd43b828c0bcc637d5d4309b4/src/integrations/auth0.js#L75

It should return `payload` or `JWTVerifyResult` not `jwt` it self.

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the validateIdToken function in auth0.js to return the payload from the JWT verification instead of the jwt itself. This change addresses the GitHub issue and improves the functionality of the code.

I also created pull request: https://github.com/irensaltali/serverlessapigateway/pull/72


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
